### ISSUE TITLE
Incorrect use of Pdeathsig for killing child on linux.

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/func-e#173]
**Describe the bug**
Right now, on Linux, we set `SysProcAttr.Pdeathsig = SIGTERM` with a comment that this will kill the child when the parent dies. This is incorrect usage to achieve the results. The correct way to use Pdeathsig would be to launch a goroutine, lock it to the OS thread, start the child in that goroutine, and don't exit the goroutine until the child exits. 

While revisiting this, we should re-check any assumptions for example that SIGTERM is the appropriate signal to catch. 

Personally, I think we should prefer behaviour mentioned in the relevant go issue on conflict as many signal related code have had problems here.

**Additional context**
See https://github.com/golang/go/issues/27505#issuecomment-713706104 for an example
See https://github.com/rootless-containers/rootlesskit/issues/65 for a discussion leading to this

**Comment by dio** [comment]
We haven't done the suggested solution specifically, since the experiment in https://gist.github.com/dio/85d51d0c199b7598cefa56cb95521537 shows: that it only matters for many children processes. However, we have added tests for making sure when killing `func-e` on Linux, we propagate SIGKILL to `envoy`. See: https://github.com/tetratelabs/func-e/pull/372.

**Comment by codefromthecrypt** [comment]
works for me. thanks for the research and if something changes in the future (like somehow we start a million envoys), we can reference this!
